//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.544
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deveel.Math.Deveel.Math {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Deveel.Math.Deveel.Math.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid rounding mode.
        /// </summary>
        internal static string math00 {
            get {
                return ResourceManager.GetString("math00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a power of ten too big.
        /// </summary>
        internal static string math01 {
            get {
                return ResourceManager.GetString("math01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scale out of range..
        /// </summary>
        internal static string math02 {
            get {
                return ResourceManager.GetString("math02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Infinite or NaN.
        /// </summary>
        internal static string math03 {
            get {
                return ResourceManager.GetString("math03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Division by zero.
        /// </summary>
        internal static string math04 {
            get {
                return ResourceManager.GetString("math04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Non-terminating decimal expansion; no exact representable decimal result..
        /// </summary>
        internal static string math05 {
            get {
                return ResourceManager.GetString("math05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Division impossible.
        /// </summary>
        internal static string math06 {
            get {
                return ResourceManager.GetString("math06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid Operation.
        /// </summary>
        internal static string math07 {
            get {
                return ResourceManager.GetString("math07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rounding necessary.
        /// </summary>
        internal static string math08 {
            get {
                return ResourceManager.GetString("math08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Overflow.
        /// </summary>
        internal static string math09 {
            get {
                return ResourceManager.GetString("math09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Underflow.
        /// </summary>
        internal static string math0A {
            get {
                return ResourceManager.GetString("math0A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a null unscaled value.
        /// </summary>
        internal static string math0B {
            get {
                return ResourceManager.GetString("math0B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Digits &lt; 0.
        /// </summary>
        internal static string math0C {
            get {
                return ResourceManager.GetString("math0C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a null RoundingMode.
        /// </summary>
        internal static string math0D {
            get {
                return ResourceManager.GetString("math0D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a bad string format.
        /// </summary>
        internal static string math0E {
            get {
                return ResourceManager.GetString("math0E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a bad precision value.
        /// </summary>
        internal static string math0F {
            get {
                return ResourceManager.GetString("math0F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a null roundingMode.
        /// </summary>
        internal static string math10 {
            get {
                return ResourceManager.GetString("math10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Radix out of range.
        /// </summary>
        internal static string math11 {
            get {
                return ResourceManager.GetString("math11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Zero length BigInteger.
        /// </summary>
        internal static string math12 {
            get {
                return ResourceManager.GetString("math12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid signum value.
        /// </summary>
        internal static string math13 {
            get {
                return ResourceManager.GetString("math13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a signum-magnitude mismatch.
        /// </summary>
        internal static string math14 {
            get {
                return ResourceManager.GetString("math14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Negative bit address.
        /// </summary>
        internal static string math15 {
            get {
                return ResourceManager.GetString("math15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Negative exponent.
        /// </summary>
        internal static string math16 {
            get {
                return ResourceManager.GetString("math16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a BigInteger divide by zero.
        /// </summary>
        internal static string math17 {
            get {
                return ResourceManager.GetString("math17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a BigInteger: modulus not positive.
        /// </summary>
        internal static string math18 {
            get {
                return ResourceManager.GetString("math18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a BigInteger not invertible..
        /// </summary>
        internal static string math19 {
            get {
                return ResourceManager.GetString("math19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a start &lt; 0: {0}.
        /// </summary>
        internal static string math1A {
            get {
                return ResourceManager.GetString("math1A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a numBits must be non-negative.
        /// </summary>
        internal static string math1B {
            get {
                return ResourceManager.GetString("math1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a bitLength &lt; 2.
        /// </summary>
        internal static string math1C {
            get {
                return ResourceManager.GetString("math1C", resourceCulture);
            }
        }
    }
}
