name: Build

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
        description: 'The version of .NET to use for the build'
        default: '10.0.x'
      os:
        required: true
        type: string
        description: 'The operating system to use for the build'
        default: 'ubuntu-latest'

jobs:
  build:
      runs-on: ${{ inputs.os }}
    
      steps:
      - uses: actions/checkout@v4
    
      - name: Setup .NET ${{ inputs.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: ${{ inputs.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore -c Release
        
      - name: Test
        run: dotnet test --no-build --verbosity normal -c Release
