name: PR Build

on:
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        dotnet-version: [ 6.0.x, 7.0.x, 8.0.x]
        os: [ubuntu-latest, windows-latest, macos-latest ]
    
    uses: ./.github/workflows/build.yml
    with:
      os: ${{ matrix.os }}
      dotnet-version: ${{ matrix.dotnet-version }}
