name: PR Build

on:
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        dotnet-version: [ 6.0.x, 7.0.x, 8.0.x]
        os: [ubuntu-latest, windows-latest, macos-latest ]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Invoke Build Workflow
      uses: ./.github/workflows/build.yml
      with:
        os: ${{ matrix.os }}
        dotnet-version: ${{ matrix.dotnet }}
    
    # - name: Emit .NET 6.0 Framework Version
    #   if: matrix.dotnet == '6.0.x'
    #   run: echo "DOTNET_FX_VERSION=net6.0" >> $GITHUB_ENV

    # - name: Emit .NET 7.0 Framework Version
    #   if: matrix.dotnet == '7.0.x'
    #   run: echo "DOTNET_FX_VERSION=net7.0" >> $GITHUB_ENV

    # - name: Emit .NET 8.0 Framework Version
    #   if: matrix.dotnet == '8.0.x'
    #   run: echo "DOTNET_FX_VERSION=net8.0" >> $GITHUB_ENV
        
    # - name: Setup .NET ${{ matrix.dotnet }} Framework
    #   uses: actions/setup-dotnet@v4
    #   with:
    #     dotnet-version: ${{ matrix.dotnet }}

    # - name: Restore dependencies
    #   run: dotnet restore
      
    # - name: Build
    #   run: dotnet build --no-restore -c Release -f ${{ env.DOTNET_FX_VERSION }}
      
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal -c Release -f ${{ env.DOTNET_FX_VERSION }}  