name: Release

permissions:
  packages: write
  contents: read

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'The version to release'
        required: true

jobs:    
  build:  
    strategy:
      fail-fast: false
      matrix: 
        dotnet-version: [ 6.0.x, 7.0.x, 8.0.x]
        os: [ubuntu-latest, windows-latest, macos-latest ]
    
    uses: ./.github/workflows/build.yml
    with:
      os: ${{ matrix.os }}
      dotnet-version: ${{ matrix.dotnet-version }}

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
  
    - name: Setup .NET 8.0 Framework
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup GitVersion
      if: github.event.inputs.version == null
      uses: gittools/actions/gitversion/setup@v1.1.1
      with:
        versionSpec: '5.x'

    - name: Determine Version
      if: github.event.inputs.version == null
      uses: gittools/actions/gitversion/execute@v1.1.1

    - name: Emit Version Environment Variables from Input
      if: github.event.inputs.version != null
      run: |
          echo "GitVersion_SemVer=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          echo "GitVersion_AssemblySemVer=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          echo "GitVersion_AssemblySemFileVer=${{ github.event.inputs.version }}.0" >> $GITHUB_ENV
          echo "GitVersion_NuGetVersionV2=${{ github.event.inputs.version }}" >> $GITHUB_ENV

    - name: Build
      run: dotnet build -c Release /p:Version="${{ env.GitVersion_SemVer }}" /p:AssemblyVersion="${{ env.GitVersion_AssemblySemVer }}" /p:FileVersion="${{ env.GitVersion_AssemblySemFileVer }}"

    - name: Pack the Nuget Packages
      run: dotnet pack -c Release --no-build --no-restore --include-symbols --include-source --output nupkgs /p:PackageVersion="${{ env.GitVersion_NuGetVersionV2 }}" 

    - name: Publish the Nuget Packages to the GitHub Package Registry
      run: dotnet nuget push **/*.nupkg --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/deveel/index.json"

    - name: Publish the Nuget Packages to the Nuget Gallery
      run: dotnet nuget push **/*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source "https://api.nuget.org/v3/index.json"